#!/bin/sh

echo ""
echo "Usage: kone configure [commands] [options]"
echo ""
echo "Commands:"
echo "  help                Show command line help." 
echo "  get                 Get a configuration value from the config file."     
echo "  list                Displays your current configuration values." 
echo "  list-profiles       List the profiles available to the CLI."
echo "  new                 Copies the default profile template and creates a new profile."  
echo "  set                 Set a configuration value from the config file."  
echo "  set-default         Sets a profile as the default config file."    
echo ""     
echo "Examples:"
echo "  kone configure new --profile qaUser"
echo "  kone configure get --setting VERSION_TAG"
echo "  kone configure get --setting DEVICE_ID --profile ios"
echo "  kone configure set --setting DEBUG --value true"      
echo "  kone configure list --profile ios-sdk-7"
echo ""
exit 3