#!/bin/sh

. "${ROOT_DIR}/utils/colors_formatting.sh"

echo ""
echo "${TEXT_BOLD}VERSION:${TEXT_NORMAL} ${COLOR_LIGHT_GRAY}${CLI_VERSION}${COLOR_NORMAL}"
echo ""
echo "${TEXT_BOLD}USAGE:${TEXT_NORMAL}" 
echo "  ${COLOR_LIGHT_GRAY}kone [options] [[command] [command-options]]${COLOR_NORMAL}"       
echo ""
echo "${TEXT_BOLD}COMMANDS:${TEXT_NORMAL}"
echo "  ${COLOR_LIGHT_GRAY}app           ${COLOR_DARK_GRAY}Facilitates a variety of device actions.${COLOR_NORMAL}"    
echo "  ${COLOR_LIGHT_GRAY}cli           ${COLOR_DARK_GRAY}Create and remove CLI commands.${COLOR_NORMAL}"  
echo "  ${COLOR_LIGHT_GRAY}configure     ${COLOR_DARK_GRAY}Configure your CLI profile options.${COLOR_NORMAL}"
echo "  ${COLOR_LIGHT_GRAY}deploy        ${COLOR_DARK_GRAY}Performs an app update and then deploys a new version to Firebase through Azure pipelines.${COLOR_NORMAL}" 
echo "  ${COLOR_LIGHT_GRAY}project       ${COLOR_DARK_GRAY}Provides mobile developers and testers with the capabilities to manage their local projects.${COLOR_NORMAL}"           
echo "  ${COLOR_LIGHT_GRAY}help          ${COLOR_DARK_GRAY}Show command line help.${COLOR_NORMAL}"           
echo ""
echo "${TEXT_BOLD}EXAMPLES:${TEXT_NORMAL}" 
echo "  ${COLOR_LIGHT_GRAY}$ kone app start-device"
echo "  $ kone app run --device ZY32298W3J --debug"
echo "  $ kone project bundle --reinstall"
echo ""
echo "  Or, simply run:"
echo "  '$ kone [command] -h|--help' for more information on a command.${COLOR_NORMAL}"
echo ""