#!/bin/sh

echo ""
echo "KONE FSM app CLI"
echo "Usage: kone [options] [[command] [command-options]]"
echo ""
echo "Options:"
echo "  --info              Prints out detailed information about a project installation and environment."    
echo "  --sdk-version       Prints out the SDK version in use."             
echo ""
echo "Commands:"
echo "  app                 Provides mobile developers and testers with the capabilities to manage their local projects."    
echo "  cli                 Create and remove CLI commands."  
echo "  configure           Configure the KONE FSM app CLI options."
echo "  deploy              Performs an app update and then deploys a new version to Firebase through Azure pipelines."            
echo "  help                Show command line help."    
echo "  version             Prints out the version of the CLI in use."            
echo ""
echo "Run 'kone [command] -h|--help' for more information on a command."
echo ""