#!/bin/sh

. "${ROOT_DIR}/utils/utils.sh"
get_theme

echo ""
echo "${COLOR_YELLOW}KONE CLI command line help.${COLOR_NORMAL}"
echo ""
echo "${COLOR_DARK_GRAY}VERSION:${COLOR_NORMAL} ${BACKGROUND_BLUE}${CLI_VERSION}${BACKGROUND_NORMAL}"
echo ""
echo "${COLOR_DARK_GRAY}USAGE:${COLOR_NORMAL}" 
echo "${COLOR_GREEN}kone${COLOR_NORMAL} ${COLOR_YELLOW}[command]${COLOR_NORMAL} ${COLOR_CYAN}[command-options]${COLOR_NORMAL} ${COLOR_MAGENTA}[arguments]${COLOR_NORMAL}"       
echo ""
echo "${COLOR_DARK_GRAY}COMMANDS:${COLOR_NORMAL}     ${COLOR_DARK_GRAY}DESCRIPTION:${COLOR_NORMAL}"
echo "${COLOR_YELLOW}app${COLOR_NORMAL}           ${COLOR_CYAN}Facilitates a variety of device actions.${COLOR_NORMAL}"
echo "${COLOR_YELLOW}cli${COLOR_NORMAL}           ${COLOR_CYAN}Create and remove CLI commands.${COLOR_NORMAL}"
echo "${COLOR_YELLOW}configure${COLOR_NORMAL}     ${COLOR_CYAN}Configure your CLI profile.${COLOR_NORMAL}"
echo "${COLOR_YELLOW}deploy${COLOR_NORMAL}        ${COLOR_CYAN}Deploy a new version of the app to Firebase through Azure pipelines.${COLOR_NORMAL}"
echo "${COLOR_YELLOW}project${COLOR_NORMAL}       ${COLOR_CYAN}Manage your local KONE FSM projects.${COLOR_NORMAL}"
echo "${COLOR_YELLOW}help${COLOR_NORMAL}          ${COLOR_CYAN}Show command line help.${COLOR_NORMAL}"
echo ""
echo "${COLOR_DARK_GRAY}EXAMPLES:${TEXT_NORMAL}" 
echo "$ ${COLOR_GREEN}kone${COLOR_NORMAL} ${COLOR_YELLOW}app${COLOR_NORMAL} ${COLOR_CYAN}start-device${COLOR_NORMAL}"
echo "$ ${COLOR_GREEN}kone${COLOR_NORMAL} ${COLOR_YELLOW}app${COLOR_NORMAL} ${COLOR_CYAN}run${COLOR_NORMAL} ${COLOR_MAGENTA}--device ZY32298W3J --debug${COLOR_NORMAL}"
echo "$ ${COLOR_GREEN}kone${COLOR_NORMAL} ${COLOR_YELLOW}project${COLOR_NORMAL} ${COLOR_CYAN}bundle${COLOR_NORMAL} ${COLOR_MAGENTA}--reinstall${COLOR_NORMAL}"
echo ""
echo "Or, simply run:"
echo "$ ${COLOR_GREEN}kone${COLOR_NORMAL} ${COLOR_YELLOW}[command]${COLOR_NORMAL} ${COLOR_MAGENTA}-h|--help${COLOR_NORMAL} for more information on a command."
echo ""
exit 3