#!/bin/sh

# theme colors used by cli
HELP_TITLE_COLOR=${COLOR_DARK_GRAY}
HELP_TEXT_COLOR=${COLOR_CYAN}
DRIVER_COLOR=${COLOR_GREEN}
COMMAND_COLOR=${COLOR_YELLOW}
COMMAND_OPTION_COLOR=${COLOR_CYAN}
ARGS_COLOR=${COLOR_MAGENTA}
VERSION_COLOR=${BACKGROUND_BLUE}