#!/bin/sh

echo ""
echo "Description: Automates mobile app deployments to the KONE Firebase instance."
echo "Usage: kone deploy [options] [[--] <additional arguments>]]"
echo ""
echo "Options:"
echo "  create-release      Creates the required release branches for the project."
echo "  help                Show command line help."
echo "  tag-release         Creates the tag to mark a release point with the configured version number."
echo ""
echo "Examples:"
echo "  kone dev diff-head"
echo "  kone dev list-branches --all"
echo "  kone dev switch-branches --main feature/http-logging-xplatform --force"
echo "  kone dev undo-changes"
echo ""
echo "Run 'kone [command] -h|--help' for more information on a command."
echo ""
exit 3