#!/bin/sh

echo ""
echo "Description: Automates mobile app deployments to the KONE Firebase instance."
echo "Usage: kone deploy [options] [[--] <additional arguments>]]"
echo ""
echo "Options:"
echo "  create-release        Creates the required release branches for the project."
echo "  diff-head             Show changes between local branches and HEAD."
echo "  list-branches         If no non-option arguments are provided, existing branches are listed."
echo "  list-tags             List all tags."
echo "  switch-branches       Updates files in the working tree to match the version in the specified branches."
echo "  tag-release           Creates the tag to mark a release point with the configured version number."
echo "  undo-changes          Resets the current branch HEAD to <COMMIT> and updates the working tree."
echo ""
echo "Examples:"
echo "  kone dev diff-head"
echo "  kone dev list-branches --all"
echo "  kone dev switch-branches --main feature/http-logging-xplatform --force"
echo "  kone dev undo-changes"
echo ""
echo "Run 'kone [command] -h|--help' for more information on a command."
echo ""
exit 3